language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"

env: AUTHOR_TESTING=1 RELEASE_TESTING=1
install: cpanm --quiet --notest Dist::Zilla && dzil authordeps | cpanm --quiet --notest && dzil listdeps | cpanm --quiet --notest
script: dzil test
