language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"

env: AUTHOR_TESTING=1 RELEASE_TESTING=1
install: cpanm Dist::Zilla && dzil authordeps --missing | cpanm --quiet --notest && dzil listdeps --missing | cpanm --quiet --notest
script: dzil test
